const Ticket = require("../../models/Ticket");
const User = require("../../models/User");
const express = require('express'); 
const auth = require("../../middleware/auth");
const Employee = require("../../models/Employee");
const router = express.Router();

router.get('/',(req,res)=>{
    res.send('ticket / called..')
})
/* 
   @Path: /api/ticket/add 
   @body: issue*, priority*,email:from token 
*/
router.post('/add',auth, async (req,res)=>{
    const {id} = req.user;
    const user = await User.findById(id);
    /* Read email from the token */
    const email = user.email;

    const {issue,priority} = req.body; 
    
    let ticket = new Ticket({
        issue,priority,email
    });

    ticket  = await ticket.save();
    
    res.send(ticket);
});

/* 
   @Path: /api/ticket/all 
   @token: manager email:from token
   @Description: Return all tickets generated by employees managed by manager 
*/
router.get('/all',auth, async (req,res)=>{
    const {id} = req.user;
    const user = await User.findById(id);
    /* Read email from the token */
    const email = user.email;

    if(!(user.role === 'MANAGER')){
        return res.status(401).json({"msg": "Unauthorized"})
    }

    /* Fetch all employees for manager(user.email) */
    const employees = await Employee.find({managerEmail: user.email});
    let tickets = [];
    for( let e of employees){
        let ticketArray = await Ticket.find({
            $and:[
                {email: e.email},{status : 'OPEN'}
            ]
        });
        tickets = [...tickets,...ticketArray];
    }

   return res.send(tickets);
});

/* 
   @Path: /api/ticket/response 
   @body: ticketId*, response*, manager email:from token
   @Description: Manager will provide the response to the ticket 
*/
router.put('/response',auth,async (req,res)=>{
    const {id} = req.user;
    const user = await User.findById(id);
    /* Read email from the token */
    const email = user.email;

    if(!(user.role === 'MANAGER')){
        return res.status(401).json({"msg": "Unauthorized"})
    }

    const {ticketId,response} = req.body; 
    let ticket = await Ticket.findById(ticketId);
    ticket.response = response; 

    ticket = await ticket.save();

    res.send(ticket);
});

/* 
   @Path: /api/ticket/status/update 
   @body: ticketId*, status*, employee email:from token
   @Description: Employee will CLOSE the ticket it had generated.  
*/
router.put('/status/update',auth,async (req,res)=>{
    const {id} = req.user;
    const user = await User.findById(id);
    /* Read email from the token */
    const email = user.email; 

    const {ticketId,status} = req.body;

    let ticket = await Ticket.findById(ticketId);
    
    /* Verify the emails from token and ticket*/
    if(!(email === ticket.email)){
        return res.status(403).json({"msg": "Forbidden"})
    }

    ticket.status=status;
    ticket = await ticket.save();

    res.send(ticket);
});

/* 
   @Path: /api/ticket/status/:status 
   @inputs: employee email:from token
   @Description: Employee will see all the tickets(OPEN/CLOSE)  
*/
router.get('/status/:status',auth,async (req,res)=>{
    const {id} = req.user;
    const user = await User.findById(id);
    
    const status = req.params['status'];

    let ticket = await Ticket.find({
        $and:[
            {email: user.email},{status: status}
        ]
    });


    res.send(ticket);
})

 
module.exports = router; 